// File generated by FlutterFire CLI.
// ignore_for_file: type=lint;
// import 'package:firebase_core/firebase_core.dart'show FirebaseOptions;
// import 'firebase_options.dart';

// ...



import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-AgrjaJwcWJmtM9OJ0LtZAdg-DzSStc',
    appId: '1:338100121088:web:b11ffba31953970a82f2e5',
    messagingSenderId: '338100121088',
    projectId: 'sustainabilityapp-3a7e0',
    authDomain: 'sustainabilityapp-3a7e0.firebaseapp.com',
    storageBucket: 'sustainabilityapp-3a7e0.firebasestorage.app',
    measurementId: 'G-VWP64E6PQ3',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLS6mZ1HOZJ5A581F5akCu0HUPZt7RnkE',
    appId: '1:338100121088:android:1b670708c13e920382f2e5',
    messagingSenderId: '338100121088',
    projectId: 'sustainabilityapp-3a7e0',
    storageBucket: 'sustainabilityapp-3a7e0.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6v5CGjQf7_ss533yLw4w2N521_RaSQM',
    appId: '1:338100121088:ios:8cd837f86d9b3f1282f2e5',
    messagingSenderId: '338100121088',
    projectId: 'sustainabilityapp-3a7e0',
    storageBucket: 'sustainabilityapp-3a7e0.firebasestorage.app',
    iosBundleId: 'com.example.sustainableApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE6v5CGjQf7_ss533yLw4w2N521_RaSQM',
    appId: '1:338100121088:ios:8cd837f86d9b3f1282f2e5',
    messagingSenderId: '338100121088',
    projectId: 'sustainabilityapp-3a7e0',
    storageBucket: 'sustainabilityapp-3a7e0.firebasestorage.app',
    iosBundleId: 'com.example.sustainableApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-AgrjaJwcWJmtM9OJ0LtZAdg-DzSStc',
    appId: '1:338100121088:web:79fbda07f7b24a3a82f2e5',
    messagingSenderId: '338100121088',
    projectId: 'sustainabilityapp-3a7e0',
    authDomain: 'sustainabilityapp-3a7e0.firebaseapp.com',
    storageBucket: 'sustainabilityapp-3a7e0.firebasestorage.app',
    measurementId: 'G-81FHV0M11Z',
  );
}

